sudo: false
dist: "xenial"
language: "python"

python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.6"
    - "3.7-dev"
    - "pypy2.7"
    - "pypy3.5"

install:
    - "pip install ."
    - "pip install -U coveralls flake8 sphinx sphinx_rtd_theme"

script:
    - "coverage run --include='more_itertools/*.py' --omit='more_itertools/tests/*' setup.py test"
    - "flake8 ."
    - "sphinx-build -W -b html docs docs/_build/html"

notifications:
  email: false

after_success:
    - "coveralls"
